### ISSUE TITLE
`make install`... :/

### ISSUE THREAD

**Issue by ahkok** [vtjnash/libwhich#10]
Can you maybe `autoscan` this and make this easy to ingest for distributions? We'd love to see at least `make install` work with a DESTDIR. Of course, autotoolizing wouldn't be too difficult, so if you're interested, please let me know and I can maybe make a PR.

**Comment by vtjnash** [comment]
I tried to, but it seemed to want a lot of complexity for turning a single `.c` input file into a single binary file (and running the test script). But I'm not that familiar with autoscan. You're welcome to make a PR to add these things.
