### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by pgajdos** [vtjnash/libwhich#14]
Hello,

I get
```
$ libwhich libz.so.1
library:
  /lib64/libz.so.1

dependencies:
  linux-vdso.so.1
  /lib64/libdl.so.2
  /lib64/libc.so.6
  /lib64/ld-linux-x86-64.so.2
+ /lib64/libz.so.1
$
```
Note the `linux-vdso.so.1` virtual iibrary in the output. Tests are not consider this possibility.

**Comment by pgajdos** [comment]
There is a patch here:
https://build.opensuse.org/package/view_file/home:pgajdos:julia/libwhich/libwhich-test.patch?expand=1
But not sure it is correct attitude.

**Comment by vtjnash** [comment]
Thanks! Yeah, for some reason it didn't used to show up in the list. I've adapted something similar to that patch that'll ignore non-absolute paths showing up in the list.

**Comment by pgajdos** [comment]
Yes, that was second possibility I was considering. Thanks a lot!
